
project_id = "xzmzfdoctqegsvppyaxg"

[functions.speech]
verify_jwt = false

[functions.transcribe]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.web-scraper]
verify_jwt = false
