// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxtzgebhtwofehdktfaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14dHpnZWJodHdvZmVoZGt0ZmFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NDQwODMsImV4cCI6MjA1OTEyMDA4M30.eGvwOP0Vnclas7Q-LRq7T7Leq2DbuQQ7aTwaakLDCHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);